-- require("git-worktree").setup {}
--
-- vim.keymap.set("n", "<leader>gct", function()
--     require('telescope').extensions.git_worktree.create_git_worktree()
-- end, { noremap = true, silent = true, expr = false })
--
-- vim.keymap.set("n", "<leader>gst", function()
--     require('telescope').extensions.git_worktree.git_worktrees()
-- end, { noremap = true, silent = true, expr = false })
--
--
-- require("telescope").load_extension("git_worktree")
