-- local lsp = require("lsp-zero").preset("recommended")
--
-- lsp.ensure_installed({
-- 	'tsserver',
-- 	'lua_ls',
-- 	'rust_analyzer',
-- 	-- 'omnisharp'
-- })
--
-- lsp.setup()
--
--
-- local cmp = require('cmp')
--
-- cmp.setup({
-- 	sources = {
-- 		{ name = 'path' },
-- 		{ name = 'nvim_lsp', max_item_count = 30 },
-- 		{ name = 'buffer',   keyword_length = 2, max_item_count = 30 },
-- 		{ name = 'luasnip',  keyword_length = 2, max_item_count = 30 },
-- 	},
-- 	mapping = {
-- 		['<CR>'] = cmp.mapping.confirm({ select = false }),
-- 	},
-- 	formatting = {
-- 		format = function(_, vim_item)
-- 			-- TODO: Remove? I don't remember what this was for
-- 			local abbr = vim_item.abbr
-- 			-- only include up to the argument table
-- 			local find_args_start = abbr:find("%(")
--
-- 			vim_item.abbr = string.sub(abbr, 1, find_args_start and find_args_start - 1 or 50)
-- 			return vim_item
-- 		end
-- 	}
-- })
--
--
-- lsp.skip_server_setup({ "rust_analyzer" })
--
-- require('lspconfig').lua_ls.setup({
-- 	settings = {
-- 		Lua = {
-- 			diagnostics = {
-- 				globals = { "Citizen", "mysql", "vim", "vector3", "vector2", "vec3", "fx_version" },
-- 			},
-- 			completion = {
-- 				autorequire = false
-- 			},
-- 			runtime = {
-- 				version = "lua 5.4",
-- 				plugin = "~/.config/lua/plugin.lua",
-- 				nonstandardSymbol = {
-- 					"+=",
-- 					"-=",
-- 					"*=",
-- 					"/=",
-- 					"`"
-- 				}
-- 			},
-- 			workspace = {
-- 				library = {
-- 					[vim.fn.expand "$vimruntime/lua"] = true,
-- 					[vim.fn.expand "$vimruntime/lua/vim/lsp"] = true,
-- 					["~/.config/lua/natives"] = true,
-- 					["~/fxserver/server-data/resources/pma-framework"] = true,
-- 					["~/fxserver/server-data/resources/oxmysql"] = true,
-- 					["~/fxserver/server/alpine/opt/cfx-server/citizen/scripting/lua"] = true,
-- 				},
-- 				type = {
-- 					weakUnionCheck = true,
-- 					weakNilCheck = true,
-- 				},
-- 				maxPreload = 100000,
-- 				preloadfilesize = 10000,
-- 			},
-- 		},
-- 	},
-- })
--
-- lsp.set_preferences({
-- 	suggest_lsp_servers = false,
-- })
--
--
-- lsp.on_attach(function(client, bufnr)
-- end)
-- vim.api.nvim_create_autocmd("FileType", {
-- 	callback = function()
-- 		local bufnr = vim.fn.bufnr('%')
-- 		vim.keymap.set("n", "<CR>", function()
-- 			vim.api.nvim_command([[execute "normal! \<cr>"]])
-- 			vim.api.nvim_command(bufnr .. 'bd')
-- 		end, { buffer = bufnr })
-- 	end,
-- 	pattern = "qf",
-- })
--
--
-- vim.diagnostic.config({
-- 	virtual_text = true,
-- 	signs = true,
-- 	update_in_insert = true,
-- 	underline = true,
-- 	severity_sort = true,
-- 	float = {
-- 		focusable = false,
-- 		style = 'minimal',
-- 		border = 'rounded',
-- 		source = 'always',
-- 		header = '',
-- 		prefix = '',
-- 	},
-- })
